import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/SideBar/sidebar";
import GlobalStylesProvider from "./providers/GlobalStylesProvider";
import ContextProviders from "./providers/ContextProviders";
import { ClerkProvider ,auth} from "@clerk/nextjs";
import Start from "./Components/Start/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {userId} = auth()
 
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer" />
      </head>
      <body className={inter.className}>
        <ContextProviders>
          <GlobalStylesProvider>
          {userId ? (
        <>
          <Sidebar />
          <div className="w-full">{children}</div>
        </>
      ) : (
        <Start />
      )}
          </GlobalStylesProvider>
        </ContextProviders>
      </body>
    </html>
    </ClerkProvider>
  );
}



